spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://mysql:3306/movie
        username: movie_user
        password: movie_pass
        driver-class-name: com.mysql.jdbc.Driver